# Ansible Inventory - Auto-generated by Terraform
# Gateway (jump host): ${gateway_instance} @ ${gateway_ip}

[gateway]
${name_prefix}-gateway ansible_host=${gateway_ip} private_ip=${gateway_secops_ip} gateway_private_ip=${gateway_private_ip} ansible_user=${ssh_user} ansible_ssh_private_key_file=${ssh_private_key_path}

[obs_stack]
${name_prefix}-obs-stack ansible_host=${obs_stack_ip} private_ip=${obs_stack_ip} ansible_user=${ssh_user} ansible_ssh_private_key_file=${ssh_private_key_path} ansible_ssh_common_args='-o ProxyJump=${ssh_user}@${gateway_ip}:22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=10'

[secops_app]
${name_prefix}-secops-app ansible_host=${secops_app_ip} private_ip=${secops_app_ip} ansible_user=${ssh_user} ansible_ssh_private_key_file=${ssh_private_key_path} ansible_ssh_common_args='-o ProxyJump=${ssh_user}@${gateway_ip}:22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=10'

[private_vm]
${name_prefix}-private-vm ansible_host=${private_vm_ip} private_ip=${private_vm_ip} ansible_user=${ssh_user} ansible_ssh_private_key_file=${ssh_private_key_path} ansible_ssh_common_args='-o ProxyJump=${ssh_user}@${gateway_ip}:22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=10'

# Anything that MUST SSH through gateway:
[behind_gateway]
${name_prefix}-obs-stack
${name_prefix}-secops-app
${name_prefix}-private-vm

[behind_gateway:vars]
ansible_ssh_private_key_file=${ssh_private_key_path}
ansible_ssh_common_args='-o ProxyJump=${ssh_user}@${gateway_ip}:22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=10 -o ServerAliveInterval=60'

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_private_key_file=${ssh_private_key_path}
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

# Convenience group (for playbooks using hosts: instances)
[instances:children]
gateway
obs_stack
secops_app
private_vm
